In [1]:
import numpy as np

In [4]:
file_path = "D:/Code/graduation_design/base_model_results/ml-1m/ACF.npy"
acf = np.load(file_path)

In [13]:
acf.shape

(834449, 102)

In [21]:
acf[834174], acf[834351]

(array([6032,  492, 1403, 2291, 2499, 1107, 2391,   55, 1283, 1749, 1132,
        1429, 1802, 1381, 2346, 1261, 1899, 1750, 2675,  854, 1141, 2347,
        1504,  111,  973, 1196,  972, 2281,   94, 1255, 2105, 2459, 1021,
        2491, 2245, 1357, 2288,  903, 2683, 2016, 1388,  734,  751, 2492,
        2404, 2055, 1965, 2054,  256, 1488, 2662, 1741, 1685, 1936,  781,
        2689, 2402, 1464, 2247, 1778, 1431, 1377,   77, 1441, 2362, 2480,
         737, 1102, 2483, 2696, 1677,  258,  184, 1738,  324, 2412, 2490,
        1108, 1277, 1351, 2405, 2256, 1829,  237, 1133, 1455, 2385, 1654,
        1296, 1499,  289, 1337, 1396,   57, 1839, 2814,   84,  240, 2276,
        2605,  248, 1263], dtype=int64),
 array([6032,  387,  237,   59,   13,  238, 1283, 1802,    9,   41,  380,
         239,  680,  504,   81,   60, 1316,   74,  734,   62,  476,  234,
         325,  254,  719,   64,   63,   12,  492,    8,  737,  249, 1357,
        1550, 1122,   76,   55,  517,  705,  708,  287, 1088, 1276,  18

In [20]:
np.unravel_index(np.argmax(acf), acf.shape)

(834351, 0)

In [24]:
file_path = "D:/Code/graduation_design/base_model_results/ml-1m/anam.npy"
anam = np.load(file_path)

In [30]:
np.unravel_index(np.argmax(anam), acf.shape), anam[834174], anam[834351]

((834174, 0),
 array([6032,  492,   59, 1141,  854, 1802, 1351, 1429,   57,  978,   76,
           9,   13, 2016, 1357, 1261,   62,  737, 1381,  492, 1107, 1749,
         504,   41,  380, 2247,   74, 1132, 1292, 1196,  237,  330,  533,
        2675,  324,   55, 1550, 1283,  325, 2492,  781, 1403,  972,   15,
          53,   24, 1021,    1,  256,   60,  184,  719,   82,  707,   85,
        1108,   77,  187,  973,  539,  238,   37,   94,   11,  185,   64,
         751, 1504,  370,   54,  974,   95, 1316,  680,  111,  333, 1241,
        1291,  234,  971,    7, 1464,  734,  249, 1736,  182,  163, 1750,
         463,  708,  461, 2346, 1277, 1148,   12,  116, 1001,  239, 1826,
        1747, 2281,   14], dtype=int64),
 array([6032,  387,   59, 1141,  854, 1802, 1351, 1429,   57,  978,   76,
           9,   13, 2016, 1357, 1261,   62,  737, 1381,  492, 1107, 1749,
         504,   41,  380, 2247,   74, 1132, 1292, 1196,  237,  330,  533,
        2675,  324,   55, 1550, 1283,  325, 2492,  781, 1