In [1]:
import numpy as np

In [13]:
file_path = "D:/Code/graduation_design/base_model_results/ml-1m/anam.npy"
acf = np.load(file_path)

In [14]:
acf.shape

(834449, 102)

In [15]:
acf[:10, :2]

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [0, 5],
       [0, 6],
       [0, 7],
       [0, 8],
       [0, 9]], dtype=int64)

In [20]:
np.unravel_index(np.argmax(acf), acf.shape)

(834351, 0)

In [24]:
file_path = "D:/Code/graduation_design/base_model_results/ml-1m/anam.npy"
anam = np.load(file_path)

In [30]:
np.unravel_index(np.argmax(anam), acf.shape), anam[834174], anam[834351]

((834174, 0),
 array([6032,  492,   59, 1141,  854, 1802, 1351, 1429,   57,  978,   76,
           9,   13, 2016, 1357, 1261,   62,  737, 1381,  492, 1107, 1749,
         504,   41,  380, 2247,   74, 1132, 1292, 1196,  237,  330,  533,
        2675,  324,   55, 1550, 1283,  325, 2492,  781, 1403,  972,   15,
          53,   24, 1021,    1,  256,   60,  184,  719,   82,  707,   85,
        1108,   77,  187,  973,  539,  238,   37,   94,   11,  185,   64,
         751, 1504,  370,   54,  974,   95, 1316,  680,  111,  333, 1241,
        1291,  234,  971,    7, 1464,  734,  249, 1736,  182,  163, 1750,
         463,  708,  461, 2346, 1277, 1148,   12,  116, 1001,  239, 1826,
        1747, 2281,   14], dtype=int64),
 array([6032,  387,   59, 1141,  854, 1802, 1351, 1429,   57,  978,   76,
           9,   13, 2016, 1357, 1261,   62,  737, 1381,  492, 1107, 1749,
         504,   41,  380, 2247,   74, 1132, 1292, 1196,  237,  330,  533,
        2675,  324,   55, 1550, 1283,  325, 2492,  781, 1